print("How many numbers do you want to add? (1-10)\n")
x = int(input())
if x == 2:
    a = int(raw_input('A='))
    b = int(raw_input('B='))
    x = (a+b)
    print(x)
if x == 3:
    a = int(raw_input('A='))
    b = int(raw_input('B='))
    c = int(raw_input('C='))
    x = (a+b+c)
    print(x)
if x == 4:
    a = int(raw_input('A='))
    b = int(raw_input('B='))
    c = int(raw_input('C='))
    d = int(raw_input('D='))
    x = (a+b+c+d)
    print(x)
if x == 5:
    a = int(raw_input('A='))
    b = int(raw_input('B='))
    c = int(raw_input('C='))
    d = int(raw_input('D='))
    e = int(raw_input('E='))
    x = (a+b+c+d+e)
    print(x)
if x == 6:
    a = int(raw_input('A='))
    b = int(raw_input('B='))
    c = int(raw_input('C='))
    d = int(raw_input('D='))
    e = int(raw_input('E='))
    f = int(raw_input('F='))
    x = (a+b+c+d+e+f)
    print(x)
if x == 7:
    a = int(raw_input('A='))
    b = int(raw_input('B='))
    c = int(raw_input('C='))
    d = int(raw_input('D='))
    e = int(raw_input('E='))
    f = int(raw_input('F='))
    g = int(raw_input('G='))
    x = (a+b+c+d+e+f+g)
    print(x)
if x == 8:
    a = int(raw_input('A='))
    b = int(raw_input('B='))
    c = int(raw_input('C='))
    d = int(raw_input('D='))
    e = int(raw_input('E='))
    f = int(raw_input('F='))
    g = int(raw_input('G='))
    h = int(raw_input('H='))
    x = (a+b+c+d+e+f+g+h)
    print(x)
if x == 9:
    a = int(raw_input('A='))
    b = int(raw_input('B='))
    c = int(raw_input('C='))
    d = int(raw_input('D='))
    e = int(raw_input('E='))
    f = int(raw_input('F='))
    g = int(raw_input('G='))
    h = int(raw_input('H='))
    i = int(raw_input('I='))
    x = (a+b+c+d+e+f+g+h+i)
    print(x)
if x == 10:
    a = int(raw_input('A='))
    b = int(raw_input('B='))
    c = int(raw_input('C='))
    d = int(raw_input('D='))
    e = int(raw_input('E='))
    f = int(raw_input('F='))
    g = int(raw_input('G='))
    h = int(raw_input('H='))
    i = int(raw_input('I='))
    j = int(raw_input('J='))
    x = (a+b+c+d+e+f+g+h+i+j)
    print(x)